# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='eemail',
        ),
    ]
