# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('paper', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
                ('way', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
    ]
